### PR TITLE
#10 - Introduce support for the OriginalScore feature boost in LambdaMART model

### PR DESCRIPTION
**Pull request by alessandrobenedetti**
Currently the OriginalScore feature is not usable by a lambdaMART model if not in the training Set.
I would suggest to add an additional param that will be as the SVM model params.

Just a scalar value and the originalScore feature.
In this way the final score coming from lambdaMart can be affected by the original score by the factor the user specified.

This will allow users to use LambdaMART models to boost documents, instead of completely re-write the score for them.

### CODE REVIEW

**Comment by alessandrobenedetti** [comment]
This is a draft, please share your opinions!
I don't want to enter the path of mixing SVM and LambdaMART, but adding the support to boost by the original score i think can give some additional flexibility.

Cheers

**Comment by jrpantony** [comment]
Hi Alessandro,

Really excited to see your interest! I definitely understand why you would want to do this. I have 2 thoughts. 
1) If you are going to heuristically boost, why limit yourself to original score? I could see cases where you add a new temporal feature (like say news heat) that you want to boost your results with immediately, but where you don't have that feature for the vast majority of your training data. 
2) I feel like rather than bring this to the highest level, it seems more like a new type of model to me. Aka perhaps it would make more sense to create a new model called "LTR model with heuristic boost" that through composition takes in a learned model as part of the parameters along with a special boost feature/parameter. An easier short term version could be "lambdaMART model with heuristic boost" that is just lambdaMART with some kind of boost applied at the end. 

I'm not sure however if this change is appropriate at the level you've put it in right now. The reason is that I imagine there will be a number of these one off cases, and in order to reduce complexity, it seems to me like it makes sense to push these specialized kinds of things to the model level. Let me know if you disagree. Cheers!,

-Josh

**Comment by alessandrobenedetti** [comment]
Hi Joshua,
let's discuss this :
1) agreed, pretty simple change
2) can you specify more in details your observations  about the level of abstraction we should operate?
 How would you ideally see this new model type configured ?  ( json side)
Is not ok configuration wise like it is?

Then, related the implementation ?
In the meantime I collect your feedback I could designa  slighly different solution with the abstracted new model type and related tests.
Will update this pull request.

Cheers

**Comment by alessandrobenedetti** [comment]
Hi Joshua,
just opened a draft Pull Request that overseed this one.
please take a look at your convenience !

Cheers

**Comment by jrpantony** [comment]
Hi Alessandro,

The other pull request seems to be almost exactly what I had in mind. Adding comments there. Once everyone is happy with that one I will accept that pull request and close this one. Cheers!,

-Josh

**Comment by mnilsson23** [comment]
Closing this older PR since PR #22 supersedes this one

**Pull request closed without merging**
